name: LinuxRelease
on:
  workflow_dispatch:
  repository_dispatch:
  push:
    branches:
      - '**'
      - '!main'
      - '!feature'
    tags:
      - '**'
    paths-ignore:
      - '**.md'
      - 'tools/**'
      - '.github/workflows/**'
      - '!.github/workflows/LinuxRelease.yml'

  pull_request:
    types: [opened, reopened, ready_for_review]
    paths-ignore:
      - '**.md'
      - 'tools/**'
      - '.github/workflows/**'
      - '!.github/workflows/LinuxRelease.yml'


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/main' || github.sha }}
  cancel-in-progress: true

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
 linux-release-aarch64:
   # Builds binaries for linux_arm64
   name: Linux (aarch64)
   if: startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/main' || github.repository != 'duckdb/duckdb'
   runs-on: ubuntu-latest
   container: ubuntu:18.04

   steps:
     - uses: actions/checkout@v3
       with:
         fetch-depth: 0
         
     - uses: ./.github/actions/ubuntu_18_setup
       with:
         aarch64_cross_compile: 1
         ccache: 1
         openssl: 1
         protobuf: 1

     - name: Build
       shell: bash
       run: |
         cd libhdfs3
         CC=aarch64-linux-gnu-gcc CXX=aarch64-linux-gnu-g++ make
         CC=aarch64-linux-gnu-gcc CXX=aarch64-linux-gnu-g++ make install

     - name: Deploy
       shell: bash
       run: |
         mv dist libhdfs3
         zip -j libhdfs3-linux-aarch64.zip libhdfs3
         python3 scripts/asset-upload-gha.py libhdfs3-linux-aarch64.zip

     - uses: actions/upload-artifact@v3
       with:
         name: libhdfs3-binaries-linux-aarch64
         path: |
           libhdfs3-linux-aarch64.zip
